---
# tasks file for zabbix-agent
- name: Install Zabbix dpkg
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"
    update_cache: true

- name: "Update the apt repository"
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install Zabbix packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Copy zabbix-agentd conf
  ansible.builtin.template:
    src: shared/templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: '0664'

- name: Start zabbix agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
